mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('polls.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls)
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.home, name='index'),
    path('<int:question_id>/', views.detail, name="detail"),
    path('<int:question_id>/results/', views.results, name="results"),
    path('<int:question_id>/vote/', views.vote, name="vote"),
    path('base/', views.base, name="home"),
    path('processes/', views.processes, name="processes"),
    path('data/', views.data, name="data"),
    path('newdata/', views.newData, name="newdata"),
    path('home/', views.home, name="home"),
    path('analytics/', views.analytics, name="analytics"),
    path('dev/', views.dev, name="dev")
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
import django_tables2 as tables


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date Published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class ExternalData(models.Model):
    Mitarbeiter_ID = models.CharField(max_length=200)
    Leistungsdatum = models.CharField(max_length=200)
    Taetigkeit = models.CharField(max_length=200)
    Kostenstelle = models.CharField(max_length=200)
    Bundesland = models.CharField(max_length=200)

    def __str__(self):
        return self.Mitarbeiter_ID


class Ausschreibungen(models.Model):
    Nummer = models.CharField(max_length=200)
    Name = models.CharField(max_length=200)
    Status = models.CharField(max_length=200)
    Auftraggeber = models.CharField(max_length=200)
    Region = models.CharField(max_length=200)
    Auftragswert = models.CharField(max_length=200)
    Beguenstigter = models.CharField(max_length=200)
    DatumNotifikation = models.CharField(max_length=200)

    def __str__(self):
        return self.Nummer


class DjangoTable(tables.Table):
    class Meta:
        model = ExternalData

polls/forms.py
from django import forms


class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView
from .models import Question, Choice, ExternalData, Ausschreibungen


def base(request):
    return render(request, 'layouts/base.html')


def main(request):
    return render(request, 'main.html')


def home(request):
    return render(request, 'layouts/home.html')


def processes(request):
    return render(request, 'layouts/processes.html')


def data(request):
    edata = Ausschreibungen.objects.all()
    context = {
        'Ausschreibungen': edata
    }
    return render(request, 'layouts/data.html', context)


def newData(request):
    return render(request, 'layouts/newData.html')


def analytics(request):
    return render(request, 'layouts/analytics.html')


def dev(request):
    return render(request, 'layouts/dev.html')


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list
    }
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You did not select a choice",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

# Create your views here.

polls/templates/include/analytics.html
{% extends 'layouts/base.html' %}

polls/templates/include/sidebar.html
<aside class="navbar-expand pt-4 " >
<div class="container-fluid p-0 position-absolute">
 <nav class="navbar-expand text-light p-0 w-100" id="sidenav-collapse-main"
      style="width: 100%;">
        <ul class="nav flex-column mt-2 my-4 pt-4 text-light sidenav_items" id="sidebar1">
            <li class="nav-item mb-1 px-3" id="side-home" style="width:100%;">

                <a class="nav-link text-white " href="/home/">

                        <i class="fas fa-home temp" style="width: 1.75em;"></i>
                        Home

                </a>
            </li>
            <li class="nav-item mb-1 px-3" id="side-processes" style="width:100%;">

                <a class="nav-link text-white " href="/processes/">

                        <i class="fas fa-cogs temp" style="width: 1.75em;"></i>
                        Processes

                </a>
            </li>
            <!--<li class="nav-item mb-1 px-3" id="side-main" style="width:100%;">

                <a class="nav-link text-white ml-auto"  href="{% url 'polls:data' %}">

                        <i class="fas fa-database temp" style="width: 1.75em;"></i>
                        Data

                </a>
            </li> -->
            <li class="nav-item mb-1 px-3" id="side-analytics" style="width:100%;">

                <a class="nav-link text-white" href="../analytics/">

                        <i class="fas fa-chart-bar temp" style="width: 1.75em;"></i>
                        Analytics

                </a>
            </li>
            <!--<li class="nav-item mb-1 px-3" style="width:100%;">
                <a class="nav-link text-white" href="#">

                        <i class="fas fa-chart-pie temp" style="width: 1.75em;"></i>
                        Inference

                </a>
            </li>
            <li class="nav-item mb-1 px-3" style="width:100%;">
                <a class="nav-link text-white" href="#">

                        <i class="fas fa-chart-line temp" style="width: 1.75em;"></i>
                        Prediction

                </a>
            </li>
            <li class="nav-item mb-1 px-3" style="width:100%;"> -->

                        {% load static %}
                       <!-- <img src="{% static 'admin/img/data1.jpg' %}" class="img-fluid pt-4"> -->
            </li>
        </ul>
  </nav>

 </div>
</aside>

polls/templates/include/topnav.html
<div class="container-fluid p-0 border-bottom sticky-top">

        <nav class="navbar navbar-expand-sm bg-white text-secondary">

            <div class="container-fluid col-2 pr-2 pl-0 border-right">
                <a class="navbar-brand text-dark">
                    {% load static %}
                       <a href="http://www.accure.at" ><img src="{% static 'admin/img/v2-green.png' %}" class="img-fluid pr-6 w-50"></a>
                </a>

                  <button class="button" type="button" data-toggle="collapse" data-target="#sidebar"
                          aria-expanded="true" aria-controls="sidebar" style="background: none; border:none;">
                    <i class="fas fa-bars" style="color: #292b2c; padding-right: 6px;"></i>
                  </button>
            </div>
            <div class="container-fluid col-10">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="#">
                        <i class="fas fa-home" style="color: #292b2c"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="#">Processes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="#">Automation</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="#">Contact</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="#">Logout</a>
                </li>

            </ul>

        </div>

        </nav>

</div>

polls/templates/layouts/analytics.html
{% extends 'layouts/base.html' %}

{% block content %}

<script>
     $( "#side-analytics" ).addClass( "active" );
     $( "#side-analytics" ).children('a').children('i').addClass( "active" );
</script>


<div class="jumbotron">
    <h3>Überblick - Ausschreibungen bis <script> document.write(new Date().toLocaleDateString()); </script></h3>
    <iframe width="100%" height="700" src="https://app.powerbi.com/reportEmbed?reportId=70a59f77-b1fd-4d83-b58f-890f296be295&autoAuth=true&ctid=ec0f0039-d243-4234-ad8f-93d005d03470&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLXdlc3QtZXVyb3BlLWUtcHJpbWFyeS1yZWRpcmVjdC5hbmFseXNpcy53aW5kb3dzLm5ldC8ifQ%3D%3D" frameborder="0" allowFullScreen="true"></iframe>
</div>

{% endblock content %}

polls/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'admin/img/favicon.ico' %}"/>

    <link rel="stylesheet" href="/static/admin/css/customized.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://unpkg.com/bpmn-js@8.9.1/dist/assets/diagram-js.css" />
    <link rel="stylesheet" href="https://unpkg.com/bpmn-js@8.9.1/dist/assets/bpmn-font/css/bpmn.css" />

    <script type="text/javascript" src="/static/admin/js/customized.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script type="text/javascript"  src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript"  src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap4.min.js"></script>


<script src="https://unpkg.com/bpmn-js@8.9.1/dist/bpmn-modeler.development.js"></script>

    <script>

    </script>



</head>
<body class="container-fluid bg-light p-0">

{% include "include/topnav.html" %}

  <main>
    <div class="container-fluid row p-0 m-0">
        <div class="container-fluid col-2 p-0 sidebar_bg collapse show position-relative" id="sidebar" >
            {% include "include/sidebar.html" %}
        </div>
        <div class="container-fluid col-10 pt-3 " style="min-height: 100vh;">
            {% block content %}{% endblock content %}
            <div class="navbar navbar-inverse navbar-fixed-bottom">
                <div class="container">
                    <p class="navbar-text">© Accure, 2022</p>
                </div>
            </div>
        </div>
    </div>
  </main>




</body>
</html>

polls/templates/layouts/data.html
{% extends 'layouts/base.html' %}

{% block content %}





<script>
$(document).ready(function(){
    $('#datatable-table').dataTable();
});
</script>


<script>
     $( "#side-main" ).addClass( "active" );
     $( "#side-main" ).children('a').children('i').addClass( "active" );
</script>




<div class="jumbotron">
  <div class="container-fluid">
    <h3>Überblick - Ausschreibungen bis <script> document.write(new Date().toLocaleDateString()); </script></h3>
    <br>
    <a href="../newdata/"><button type="button" class="nav-link btn btn-dark">add new Project</button></a>
    <br>
    <br>

 <!-- <input class="shadow" type="text" id="myInput" onkeyup="filterTable()" placeholder="Search for (Ausschreibungs-) Nummer ..."> -->
<!--  <div class="tableFixHead mt-4" id="datatable-div" style="height: 50vh; overflow: auto;"> -->


    <table id="datatable-table" class="table table-striped table-bordered" style="width:100%" >
      <thead>
        <tr>
          <th>#</th>
          <th>Nummer</th>
          <th>Name</th>
          <th>Status</th>
          <th>Auftraggeber</th>
          <th>Auftragswert</th>
          <th>Datum</th>
        </tr>
      </thead>
      <tbody>
        {% for AS in Ausschreibungen %}
          <tr>
            <td>{{ AS.id }}</td>
            <td>{{ AS.Nummer }}</td>
            <td>{{ AS.Name }}</td>
            <td>{{ AS.Status }}</td>
            <td>{{ AS.Auftraggeber }}</td>
            <td>{{ AS.Auftragswert }}</td>
            <td>{{ AS.DatumNotifikation }}</td>
          </tr>
        {% endfor %}
      </tbody>
      </table>
  </div>





 <!-- </div>   -->


</div>

{% endblock content %}

polls/templates/layouts/dev.html
{% extends 'layouts/base.html' %}

{% block content %}

<div class="jumbotron">

    <div class="table-responsive">
    <table id="myTable" class="table table-striped" width="100%">
        <thead>
          <tr>
            <th>ENO</th>
            <th>EMPName</th>
            <th>Country</th>
            <th>Salary</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>001</td>
            <td>Anusha</td>
            <td>India</td>
            <td>10000</td>
          </tr>
          <tr>
            <td>002</td>
            <td>Charles</td>
            <td>United Kingdom</td>
            <td>28000</td>
          </tr>
          <tr>
            <td>003</td>
            <td>Sravani</td>
            <td>Australia</td>
            <td>7000</td>
          </tr>
           <tr>
            <td>004</td>
            <td>Amar</td>
            <td>India</td>
            <td>18000</td>
          </tr>
          <tr>
            <td>005</td>
            <td>Lakshmi</td>
            <td>India</td>
            <td>12000</td>
          </tr>
                  <tr>
            <td>005</td>
            <td>Lakshmi</td>
            <td>India</td>
            <td>12000</td>
          </tr>
                  <tr>
            <td>005</td>
            <td>Lakshmi</td>
            <td>India</td>
            <td>12000</td>
          </tr>
                  <tr>
            <td>005</td>
            <td>Lakshmi</td>
            <td>India</td>
            <td>12000</td>
          </tr>
                  <tr>
            <td>005</td>
            <td>Lakshmi</td>
            <td>India</td>
            <td>12000</td>
          </tr>
                  <tr>
            <td>005</td>
            <td>Lakshmi</td>
            <td>India</td>
            <td>12000</td>
          </tr>
                  <tr>
            <td>005</td>
            <td>Lakshmi</td>
            <td>India</td>
            <td>12000</td>
          </tr>
                  <tr>
            <td>005</td>
            <td>Lakshmi</td>
            <td>India</td>
            <td>12000</td>
          </tr>
                  <tr>
            <td>005</td>
            <td>Lakshmi</td>
            <td>India</td>
            <td>12000</td>
          </tr>
                  <tr>
            <td>005</td>
            <td>Lakshmi</td>
            <td>India</td>
            <td>12000</td>
          </tr>
                  <tr>
            <td>005</td>
            <td>Lakshmi</td>
            <td>India</td>
            <td>12000</td>
          </tr>
        </tbody>
    </table>
    </div>


    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script type="text/javascript"  src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript"  src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <script>
    $(document).ready(function(){
        $('#myTable').dataTable();
    });
    </script>

</div>

{% endblock content %}

polls/templates/layouts/home.html
{% extends 'layouts/base.html' %}

{% block content %}

<script>
     $( "#side-home" ).addClass( "active" );
     $( "#side-home" ).children('a').children('i').addClass( "active" );
</script>


<div class="jumbotron">
  <div class="container-fluid">
    <h3>Welcome to Accure Process-Analytics</h3>
    <p>Evaluate your potential for automation</p>
    <hr>
    <h4>What would you like to do?</h4>
    <div class="container-fluid row">
      <div class="hovereffect container-fluid col-4 p-3">
        <p>Add a <b style="color:#1C3749;">new process </b> </li></p>
        {% load static %}
        <img class="rounded mx-auto img-fluid h-75 w-100 shadow" src="{% static 'admin/img/newProcess.jpg' %}" alt="My image">
        <div class="overlay">
           <h2>add new process</h2>
           <a class="info" href="/processes/">click here</a>
        </div>
      </div>
      <div class="hovereffect container-fluid col-4 p-3">
        <p>Edit your <b style="color:#1C3749;">current processes</b></p>
        {% load static %}
        <img class="rounded mx-auto img-fluid h-75 w-100 shadow" src="{% static 'admin/img/editProcess.jpg' %}" alt="My image">
        <div class="overlay">
           <h2>edit process</h2>
           <a class="info" href="#">click here</a>
        </div>
      </div>
      <div class="hovereffect my-gallery container-fluid col-4 p-3">
        <p>Evaluate your <b style="color:#1C3749;">automation potential</b></p>
        {% load static %}
        <img class="rounded mx-auto img-fluid h-75 w-100 shadow" src="{% static 'admin/img/evalProcess.jpg' %}" alt="My image">
        <div class="overlay">
           <h2>evaluate potential</h2>
           <a class="info" href="#">click here</a>
        </div>
      </div>
    </div>
  </div>














<!--
    <p>The navbar-expand-xl|lg|md|sm class determines when the navbar should stack vertically (on extra large, large, medium or small screens).</p>

    <p class="text-primary">.text-primary</p>
    <p class="text-secondary">.text-secondary</p>
    <p class="text-success">.text-success</p>
    <p class="text-danger">.text-danger</p>
    <p class="text-warning">.text-warning</p>
    <p class="text-info">.text-info</p>
    <p class="text-light bg-dark">.text-light</p>
    <p class="text-dark">.text-dark</p>
    <p class="text-muted">.text-muted</p>
    <p class="text-white bg-dark">.text-white</p>
  </div>
-->

</div>



{% endblock content %}

polls/templates/layouts/newData.html
{% extends 'layouts/base.html' %}

{% block content %}

<script>
     $( "#side-main" ).addClass( "active" );
     $( "#side-main" ).children('a').children('i').addClass( "active" );
</script>




<div class="jumbotron">
  <div class="container-fluid">
    <h3>Add a new project</h3>

    <br>
    <form>
      <div class="form-group">
        <label for="newNUmmer">Nummer</label>
        <input type="text" class="form-control shadow" id="newNUmmer" placeholder="2021-123456">
      </div>
      <div class="form-group">
        <label for="newName">Name</label>
        <input type="text" class="form-control shadow" id="newName" placeholder="">
      </div>
      <div class="form-group">
        <label for="newStatus">Status</label>
        <select class="form-control shadow" id="newStatus">
          <option>Offen</option>
          <option>Vergeben</option>
        </select>
      </div>
      <div class="form-group">
        <label for="nweSupplier">Auftraggeber</label>
        <input type="text" class="form-control shadow" id="nweSupplier" placeholder="">
      </div>
      <div class="form-group">
        <label for="newSumme">Auftragswert</label>
        <input type="text" class="form-control shadow" id="newSumme" placeholder="">
      </div>
      <div class="form-group">
        <label for="newDate">Datum</label>
        <input type="text" class="form-control shadow" id="newDate" placeholder="">
      </div>

      <div class="form-group">
        <label for="newComment">Comment</label>
        <textarea class="form-control shadow" id="newComment" rows="3"></textarea>
      </div>

    </form>

 <!-- <input class="shadow" type="text" id="myInput" onkeyup="filterTable()" placeholder="Search for (Ausschreibungs-) Nummer ..."> -->
<!--  <div class="tableFixHead mt-4" id="datatable-div" style="height: 50vh; overflow: auto;"> -->

  <a href="../data/"><button type="button" class="nav-link btn btn-dark">submit</button></a>
  </div>






 <!-- </div>   -->


</div>

{% endblock content %}

polls/templates/main.html
{% extends 'layouts/base.html' %}

{% block content %}

<script>
     $( "#side-main" ).addClass( "active" );
     $( "#side-main" ).children('a').children('i').addClass( "active" );
</script>


<div class="jumbotron">
  <div class="container-fluid">
    <h3>Basic Navbar Example</h3>

    


    <p class="text-primary">.text-primary</p>
    <p class="text-secondary">.text-secondary</p>
    <p class="text-success">.text-success</p>
    <p class="text-danger">.text-danger</p>
    <p class="text-warning">.text-warning</p>
    <p class="text-info">.text-info</p>
    <p class="text-light bg-dark">.text-light</p>
    <p class="text-dark">.text-dark</p>
    <p class="text-muted">.text-muted</p>
    <p class="text-white bg-dark">.text-white</p>
  </div>


</div>

{% endblock content %}

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1> {{ question }} </h1>


    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}" > {{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% load static %}
<img src="{% static 'admin/img/data1.jpg' %}" alt="My image">
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>{{ question.question_text }}</h1>

  <ul>
  {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
  {% endfor %}
  </ul>

  <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>